//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tool.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_MYFORM                      310
#define IDD_UNITTOOL                    311
#define IDD_MAPTOOL                     312
#define IDD_DIALOG1                     313
#define IDD_DIALOG_TAB1                 313
#define IDD_MAPTOOL_SUBDLG              314
#define IDD_DIALOG_TAB2                 315
#define IDD_UNIT_PLAYER                 317
#define IDD_UNIT_MONSTER                318
#define IDD_DIALOG4                     319
#define IDD_UNIT_ITEM                   319
#define IDD_DIALOG2                     323
#define IDD_TILETOOL                    323
#define IDI_ICON6                       330
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT5                       1005
#define IDC_BUTTON2                     1007
#define IDC_RADIO1                      1008
#define IDC_RADIO2                      1009
#define IDC_RADIO3                      1010
#define IDC_BUTTON_MONSTER_ANI_NEW      1010
#define IDC_BUTTON_MONSTER_ANI_DEL      1011
#define IDC_CHECK1                      1012
#define IDC_BUTTON_MONSTER_ANI_PLAYBTN  1012
#define IDC_CHECK2                      1013
#define IDC_BUTTON_MONSTER_ANI_DEL2     1013
#define IDC_BUTTON_MONSTER_ANI_STOP_2   1013
#define IDC_CHECK3                      1014
#define IDC_BUTTON3                     1015
#define IDC_BUTTON4                     1019
#define IDC_EDIT6                       1020
#define IDC_BUTTON5                     1021
#define IDC_BUTTON6                     1022
#define IDC_TAB1                        1022
#define IDC_SLIDER1                     1024
#define IDC_SLIDER1_MAP                 1024
#define IDC_TAB_UNIT                    1025
#define IDC_SLIDER2_MAP                 1025
#define IDC_LIST_MONSTER                1026
#define IDC_BUTTON_MONSTER_NEW          1027
#define IDC_BUTTON_MONSTER_DELETE       1028
#define IDC_BUTTON_MONSTER_EDIT         1029
#define IDC_BUTTON_MONSTER_SAVE         1030
#define IDC_STATIC_MONSTER_TRANSFORM    1031
#define IDC_STATIC_MONSTER_STAT         1032
#define IDC_STATIC_MONSTER_COLLIDER     1033
#define IDC_BUTTON_MONSTER_SAVE2        1033
#define IDC_STATIC_MONSTER_ANIMATION    1034
#define IDC_BUTTON_MONSTER_INIT         1035
#define IDC_LIST4                       1038
#define IDC_LIST_MONSTER_TEXTURE        1038
#define IDC_STATIC_MONSTER_POS          1039
#define IDC_STATIC_MONSTER_ROT          1040
#define IDC_STATIC_MONSTER_SCL          1041
#define IDC_EDIT_MONSTER_POS_X          1042
#define IDC_STATIC_MONSTER_TRANS_X      1043
#define IDC_EDIT_MONSTER_POS_Y          1044
#define IDC_EDIT_MONSTER_POS_Z          1045
#define IDC_EDIT_MONSTER_ROT_X          1046
#define IDC_EDIT_MONSTER_ROT_Y          1047
#define IDC_EDIT_MONSTER_ROT_Z          1048
#define IDC_EDIT_MONSTER_SCL_X          1049
#define IDC_EDIT_MONSTER_SCL_Y          1050
#define IDC_EDIT_MONSTER_SCL_Z          1051
#define IDC_STATIC_MONSTER_TRANS_Y      1052
#define IDC_STATIC_MONSTER_TRANS_Z      1053
#define IDC_EDIT_MONSTER_NAME           1054
#define IDC_STATIC_MONSTER_TOOL_BTN     1055
#define IDC_STATIC_MONSTER_STAT_HP      1056
#define IDC_STATIC_MONSTER_STAT_AD      1057
#define IDC_STATIC_MONSTER_STAT_SPEED   1058
#define IDC_BUTTON4_TILE                1058
#define IDC_EDIT_MONSTER_STAT_HP_VALUE  1059
#define IDC_EDIT_MONSTER_STAT_AD_VALUE  1060
#define IDC_EDIT_MONSTER_STAT_SPEED_VALUE 1061
#define IDC_STATIC_MONSTER_STAT_TYPE    1062
#define IDC_SLIDER_MONSTER_HP           1063
#define IDC_SLIDER_MONSTER_AD           1064
#define IDC_SLIDER_MONSTER_HP3          1065
#define IDC_SLIDER_MONSTER_SPEED        1065
#define IDC_LIST_TILE                   1066
#define IDC_COMBO_TILE                  1067
#define IDC_BUTTON2_TILE                1068
#define IDC_BUTTON3_TILE                1069
#define IDC_BUTTON_TILE                 1070
#define IDC_SPIN_TILE                   1071
#define IDC_STATIC_TILE                 1072
#define IDC_MAP_OBJ_COMBO_TYPE          1091
#define IDC_MAP_OBJ_LISTBOX_UNIT        1092
#define IDC_STATIC_MAP_UNT_TYPE         1096
#define IDC_STATIC_MAP_UNIT_NAME_SEARCH 1097
#define IDC_EDIT_MAP_UNIT_NAME_SEARCH_EDIT 1098
#define IDC_RADIO1_MAP                  1099
#define IDC_RADIO2_MAP                  1100
#define IDC_STATIC20_MAP                1101
#define IDC_STATIC5_MAP                 1183
#define IDC_STATIC6_MAP                 1184
#define IDC_STATIC7_MAP                 1185
#define IDC_COMBO2_MAP                  1186
#define IDC_STATIC8_MAP                 1187
#define IDC_STATIC9_MAP                 1188
#define IDC_EDIT4_MAP                   1189
#define IDC_EDIT5_MAP                   1190
#define IDC_BUTTON2_MAP                 1191
#define IDC_BUTTON3_MAP                 1192
#define IDC_BUTTON4_MAP                 1193
#define IDC_STATIC10_MAP                1194
#define IDC_STATIC9_MAP3                1195
#define IDC_STATIC10_MAP2               1195
#define IDC_STATIC11_MAP                1196
#define IDC_STATIC10_MAP3               1197
#define IDC_BUTTON_MONSTER_ANI_PUSH     1283
#define IDC_BUTTON_MONSTER_SAVE_DB      1284
#define IDC_STATIC_MONSTER_ANIMATOR     1286
#define IDC_BUTTON_MONSTER_ANI_PLAY     1287
#define IDC_BUTTON_MONSTER_ANI_STOP     1288
#define IDC_RADIO_MONSTER_LOOP          1289
#define IDC_EDIT_MONSTER_ANI_TIME       1290
#define ID_TIMER                        1300
#define IDC_STATIC_MAPSUB               1591
#define IDC_STATIC2_MAPSUB              1592
#define IDC_STATIC1_MAP                 2072
#define IDC_STATIC2_TILE                2073
#define IDC_STATIC2_MAP                 2073
#define IDC_STATIC3_MAP                 2074
#define IDC_CHECK2_TILE                 2075
#define IDC_LIST1_MAP                   2075
#define IDC_STATIC4_MAP                 2077
#define IDC_BUTTON_MONSTER_TEX_LOAD     3001
#define IDC_COMBO_MONSTER_TYPE          3003
#define IDC_STATIC_MONSTER_STATIC_NAME  3004
#define IDC_STATIC_MONSTER_DB_LIST      3006
#define IDC_CHECK3_TILE                 3007
#define IDC_LIST1                       3008
#define IDC_LIST1_MONSTER_ANI_DB        3009
#define IDC_CHECK1_TILE                 3010
#define IDC_EDIT_TILE                   4077
#define IDC_STATIC_MONSTER_ANI_TEXTURE_LIST 4078
#define IDC_STATIC3_TILE                4079
#define IDC_COMBO1_MAP                  5078
#define IDC_STATIC_MONSTER_ANIMATION_LIST 5079
#define IDC_EDIT1_TILE                  6179
#define IDC_BUTTON1                     6279
#define IDC_BUTTON1_MAP                 6379
#define IDC_EDIT1_TILE2                 6480
#define IDC_BUTTON2_TILE2               6580
#define IDC_EDIT1_MAP                   7080
#define IDC_EDIT2_TILE                  7081
#define IDC_EDIT2_MAP                   7082
#define IDC_COMBO_MONSTER_STATE         8080
#define IDC_COMBO_MONSTER_DIR           8082
#define IDC_STATIC_MONSTER_TEXTURE      9082
#define IDC_STATIC_MOSTER_LIST_DRAG     9083
#define IDC_EDIT3_MAP                   9084
#define ICO_PLAYER_AMAZON               24464
#define ICO_PLAYER_ASSASSIN             24465
#define ICO_PLAYER_BAVARIAN             24466
#define ICO_PLAYER_NECROMANCER          24467
#define ICO_PLAYER_PALADIN              24468
#define ICO_PLAYER_SORCERESS            24469
#define ICO_MONSTER_DIABLO              25466
#define ICO_MONSTER_GOLEM               25467
#define ICO_MONSTER_PATMONSTER          25468
#define ICO_MONSTER_VIPER               25469

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        335
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
